# --- Makefile cho EmptyOS (Tối ưu cho iSH) ---
CC = gcc
AS = nasm
LD = ld

CFLAGS = -m32 -ffreestanding -O0 -fno-stack-protector -fno-pie
LDFLAGS = -m elf_i386 -T linker.ld
ASFLAGS = -f elf32

all: iso

kernel.bin: boot.o kernel.o
	$(LD) $(LDFLAGS) boot.o kernel.o -o kernel.bin

boot.o: boot.asm
	$(AS) $(ASFLAGS) boot.asm -o boot.o

kernel.o: kernel.c
	$(CC) $(CFLAGS) -c kernel.c -o kernel.o

iso: kernel.bin
	mkdir -p iso/boot/grub
	cp kernel.bin iso/boot/kernel.bin
	echo 'set timeout=0' > iso/boot/grub/grub.cfg
	echo 'set default=0' >> iso/boot/grub/grub.cfg
	echo 'menuentry "EmptyOS" {' >> iso/boot/grub/grub.cfg
	echo '  multiboot /boot/kernel.bin' >> iso/boot/grub/grub.cfg
	echo '  boot' >> iso/boot/grub/grub.cfg
	echo '}' >> iso/boot/grub/grub.cfg
	grub-mkrescue -o emptyos.iso iso
	@echo "======================================"
	@echo "  HOAN THANH: emptyos.iso da tao xong!"
	@echo "======================================"

clean:
	rm -rf *.o kernel.bin iso emptyos.iso